CREATE TABLE
    "user_mission" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        mission_id bigint NOT NULL,
        "status" entity_status NOT NULL DEFAULT 'LOCKED',
        "is_current" boolean NOT NULL DEFAULT false,
        "best_result" score,
        CONSTRAINT pk_user_mission PRIMARY KEY (id),
        CONSTRAINT fk_user_mission_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_mission_mission FOREIGN KEY (mission_id) REFERENCES "mission" (id) ON DELETE CASCADE,
        CONSTRAINT uk_user_mission UNIQUE (user_id, mission_id)
    );