CREATE TABLE
    "attempt" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_mission_id bigint NOT NULL,
        "start_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "end_at" timestamp,
        "result" score,
        CONSTRAINT pk_attempt PRIMARY KEY (id),
        CONSTRAINT fk_attempt_user_mission FOREIGN KEY (user_mission_id) REFERENCES "user_mission" (id) ON DELETE CASCADE,
        CONSTRAINT ck_user_mission_attempt CHECK ("end_at" >= "start_at")
    );