CREATE TABLE
    "question" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        mission_id bigint NOT NULL,
        "content" text NOT NULL,
        "explanation" text NOT NULL,
        "order" int NOT NULL,
        CONSTRAINT pk_question PRIMARY KEY (id),
        CONSTRAINT fk_question_mission FOREIGN KEY (mission_id) REFERENCES "mission" (id) ON DELETE CASCADE,
        CONSTRAINT uk_question_mission_order UNIQUE (mission_id, "order")
    );