CREATE TYPE level_label AS ENUM (
    'ALUMINIUM_I',
    'ALUMINIUM_II',
    'ALUMINIUM_III',
    'IRON_I',
    'IRON_II',
    'IRON_III',
    'NICKEL_I',
    'NICKEL_II',
    'NICKEL_III',
    'PALLADIUM_I',
    'PALLADIUM_II',
    'PALLADIUM_III'
);

CREATE TYPE planet_label AS ENUM ('VARIABILI', 'BIFURCA_9', 'CICLUS', 'MATRX_0');

CREATE TYPE entity_status AS ENUM ('LOCKED', 'UNLOCKED', 'COMPLETED');