CREATE TABLE
    "user" (
               id bigint GENERATED BY DEFAULT AS IDENTITY,
               "username" varchar(255) NOT NULL,
               "email" varchar(255) NOT NULL,
               "password" varchar(255) NOT NULL,
               level_id bigint NOT NULL DEFAULT 1,
               "xp" xp NOT NULL DEFAULT 0,
               "oxygen" oxygen NOT NULL DEFAULT 10,
               CONSTRAINT pk_user PRIMARY KEY (id),
               CONSTRAINT fk_user_level FOREIGN KEY (level_id) REFERENCES "level" (id),
               CONSTRAINT uk_user_email UNIQUE ("email")
);