CREATE TABLE
    "planet" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        "name" planet_label NOT NULL,
        "description" text NOT NULL,
        "content" text NOT NULL,
        "order" int NOT NULL,
        "xp_bonus" xp NOT NULL,
        CONSTRAINT pk_planet PRIMARY KEY (id),
        CONSTRAINT uk_planet_name UNIQUE ("name"),
        CONSTRAINT uk_planet_order UNIQUE ("order")
    );