CREATE TABLE
    "user_planet" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        user_id bigint NOT NULL,
        planet_id bigint NOT NULL,
        "status" entity_status NOT NULL DEFAULT 'LOCKED',
        "is_current" boolean NOT NULL DEFAULT false,
        CONSTRAINT pk_user_planet PRIMARY KEY (id),
        CONSTRAINT fk_user_planet_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE,
        CONSTRAINT fk_user_planet_planet FOREIGN KEY (planet_id) REFERENCES "planet" (id) ON DELETE CASCADE,
        CONSTRAINT uk_user_planet UNIQUE (user_id, planet_id)
    );