spring:
  application:
    name: nexus
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  data:
    web:
      pageable:
        page-serialization-mode: via-task

jwt:
  public:
    key: ${JWT_PUBLIC_KEY}
  private:
    key: ${JWT_PRIVATE_KEY}

server:
  port: 8080
  error:
    include-message: always