CREATE TABLE
    "alternative" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        question_id bigint NOT NULL,
        "content" text NOT NULL,
        "is_correct" boolean NOT NULL DEFAULT false,
        CONSTRAINT pk_alternative PRIMARY KEY (id),
        CONSTRAINT fk_alternative_question FOREIGN KEY (question_id) REFERENCES "question" (id) ON DELETE CASCADE,
        CONSTRAINT uk_alternative_content UNIQUE (question_id, "content")
    );