CREATE TABLE
    "answer" (
                 id bigint GENERATED BY DEFAULT AS IDENTITY,
                 attempt_id bigint NOT NULL,
                 question_id bigint NOT NULL,
                 alternative_id bigint NOT NULL,
                 CONSTRAINT pk_user_answer PRIMARY KEY (id),
                 CONSTRAINT fk_user_answer_attempt FOREIGN KEY (attempt_id) REFERENCES "attempt" (id) ON DELETE CASCADE,
                 CONSTRAINT fk_user_answer_question FOREIGN KEY (question_id) REFERENCES "question" (id) ON DELETE CASCADE,
                 CONSTRAINT fk_user_answer_alternative FOREIGN KEY (alternative_id) REFERENCES "alternative" (id) ON DELETE CASCADE,
                 CONSTRAINT uk_user_answer UNIQUE (attempt_id, question_id)
);