CREATE TABLE
    "level" (
                id bigint GENERATED BY DEFAULT AS IDENTITY,
                "name" level_label NOT NULL,
                "description" text,
                "order" int NOT NULL,
                "xp_bonus" xp NOT NULL,
                "xp_required" xp NOT NULL,
                CONSTRAINT pk_level PRIMARY KEY (id),
                CONSTRAINT uk_level_label UNIQUE ("name"),
                CONSTRAINT uk_level_order UNIQUE ("order")
);