CREATE TABLE
    "mission" (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        planet_id bigint NOT NULL,
        "name" varchar(255) NOT NULL,
        "description" text NOT NULL,
        "content" text NOT NULL,
        "order" int NOT NULL,
        "xp_bonus" xp NOT NULL,
        CONSTRAINT pk_mission PRIMARY KEY (id),
        CONSTRAINT fk_mission_planet FOREIGN KEY (planet_id) REFERENCES "planet" (id) ON DELETE CASCADE,
        CONSTRAINT uk_mission_planet_name UNIQUE (planet_id, "name"),
        CONSTRAINT uk_mission_planet_order UNIQUE (planet_id, "order")
    );